"""empty message

Revision ID: 40708990da63
Revises: ba6075614bdf
Create Date: 2023-10-05 05:56:12.731603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40708990da63'
down_revision = 'ba6075614bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint('note_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_constraint('quote_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('quote_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('note_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
